let lessons=[{
    id:0,
    name:"Cinematography",
    details:"2 weeks self paced learning ",
    image:"https://i.pinimg.com/originals/da/c5/67/dac56711e75ef7ec7f194f2adcb0fdd0.png",
    price:"$120" ,
    Location:"Dubai,UAE",
    inventory:5,

},
{
    id:1,
    name:"Tennis Coaching",
    details:"Live coaches from London",
    image:"https://cdn.dribbble.com/users/1518862/screenshots/5823201/tennis.png",
    price:  "$120" ,
    Location:"Dubai,UAE",
    inventory:5,
},
{
    id:2,
    details:"3 weeks course with learning materials",
    name:"Illustrations and Design",
    image:"https://miro.medium.com/max/2560/1*9UN-8OUzyVJBaKiVNX5dig.png",
    price: "$230" ,
    Location:"Dubai,UAE",
    inventory:5,
},
{
    id:3,
    name:"React and React Native",
    details:"Javascript,Html Building apps with React",
    image:"https://media.istockphoto.com/vectors/programming-code-application-window-vector-id1124838925?k=6&m=1124838925&s=612x612&w=0&h=TbuwIMLPlZxN9jbuTcJanRwX33tkgNF7_PiIPvpPVm4=",
    price:  "$120" ,
    Location:"Dubai,UAE",
    inventory:5,
    },
 {
    id:4,
    details:"Reham",
    name:"Virtual Reality",
    image:"https://i.pinimg.com/originals/b3/90/ce/b390ceab2d88238a0c8903f12e18d79a.jpg",
    price:  "$120" ,
    Location:"Dubai,UAE",
    inventory:5,
},
{
    id:5,
    details:"Reham",
    price:  "$120" ,
    Location:"Dubai,UAE",
    inventory:5,
    },
    {
        id:6,
        details:"Reham",
        price:  "$120" ,
        Location:"Dubai,UAE",
        inventory:5,
        },
        {
            id:7,
            details:"Reham",
            price:  "$120" ,
            Location:"Dubai,UAE",
            inventory:5,
            },{
                id:8,
                details:"Reham",
                price:  "$120" ,
                Location:"Dubai,UAE",
                inventory:5,
                },
                {
                    id:9,
                    details:"Reham",
                    price:  "$120" ,
                    Location:"Dubai,UAE",
                    inventory:5,
                    },
                    {
                        id:10,
                        details:"Reham",
                        price:  "$120" ,
                        Location:"Dubai,UAE",
                        inventory:5,
                        },
                        {
                            id:11,
                            details:"Reham",
                            price:  "$120" ,
                            Location:"Dubai,UAE",
                            inventory:5,
                            },
    
]