let lessons=[{
    id:0,
    name:"Cinematography",
    details:"2 weeks self paced learning ",
    image:"https://i.pinimg.com/originals/da/c5/67/dac56711e75ef7ec7f194f2adcb0fdd0.png",
    price: 120 ,
    Location:"New York ,Usa",
    inventory:5,

},
{
    id:1,
    name:"Tennis Coaching",
    details:"Live coaches from London",
    image:"https://cdn.dribbble.com/users/1518862/screenshots/5823201/tennis.png",
    price:  120 ,
    Location:"Dubai,UAE",
    inventory:5,
},
{
    id:2,
    details:"3 weeks course with learning materials",
    name:"Illustrations and Design",
    image:"https://miro.medium.com/max/2560/1*9UN-8OUzyVJBaKiVNX5dig.png",
    price: 230 ,
    Location:"California,USA",
    inventory:5,
},
{
    id:3,
    name:"Python programming",
    details:"Games on Python , Basics of coding",
    image:"https://media.istockphoto.com/vectors/programming-code-application-window-vector-id1124838925?k=6&m=1124838925&s=612x612&w=0&h=TbuwIMLPlZxN9jbuTcJanRwX33tkgNF7_PiIPvpPVm4=",
    price:  120 ,
    Location:"Dubai,UAE",
    inventory:5,
    },
 {
    id:4,
    details:"Introduction to Robotics and Virtual Reality",
    name:"Virtual Reality",
    image:"https://i.pinimg.com/originals/b3/90/ce/b390ceab2d88238a0c8903f12e18d79a.jpg",
    price:  120 ,
    Location:"Dubai,UAE",
    inventory:5,
},
{
    id:5,
    details:"Basic cycling course for all ages",
    name:"Cycling Lessons",
    image:"https://img.graphicsurf.com/2020/08/Back-to-school-autumn-illustration.jpg",
    price:  80 ,
    Location:"London",
    inventory:5,
    },
    {
        id:6,
        details:"Sessions with the coach sasa",
        name:"Basketball",
        image:"https://kit8.net/images/thumbnails/580/386/detailed/4/basketball_players@2x.png",
        price:  300 ,
        Location:"Abudhabi, Uae",
        inventory:5,
        },
        {
            id:7,
            details:"3 Hour Swimming lesson",
            name:"Swimming Course at Nasra",
            image:"https://previews.123rf.com/images/cosmaa/cosmaa1802/cosmaa180200004/94716298-vector-cartoon-illustration-of-horizontal-illustration-with-swimmers-in-swimming-pool-woman-and-man-.jpg",
            price:  70 ,
            Location:"Fujairah,UAE",
            inventory:5,
            },{
                id:8,
                details:"1 hour dance session with coach Rocky",
                name:"Dance Mania with Rocky",
                image:"https://i.pinimg.com/originals/8b/d8/87/8bd887b68ae6a14a16adc74e1eac33d7.jpg",
                price:  40 ,
                Location:"Sharjah,Uae",
                inventory:8,
                },
                {
                    id:9,
                    details:"Real Football Training weekly",
                    name:"Football Weekly Mania ",
                    image:"https://images.squarespace-cdn.com/content/v1/5aec5506da02bc18cae0f50d/1549652774334-699ZBBDA2LHOGRRQJB81/ke17ZwdGBToddI8pDm48kEudsjGS8xc-xRaqByyRr6x7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1Ufhpej1qtkadBMCMIJZ6HRgwYRyyv3prUj9vUq9rSU4eaLJgimyKlpluUohcN8RoZQ/APPLE_LONDON_SOCCER2_JAY_FLETCHER.jpg",
                    price:  110 ,
                    Location:"Al ain,UAE",
                    inventory:5,
                    },
                    {
                        id:10,
                        details:"How to manage time effectively",
                        name:"Time Manangement",
                        image:"https://miro.medium.com/max/800/0*u-Kxj7id7WBvj5BS.jpg",
                        price:  10 ,
                        Location:"Togo,Africs",
                        inventory:6,
                        },
                        {
                            id:11,
                            details:"Learn more about space and planets",
                            name:"Planets and Space Exploration",
                            image:"https://image.freepik.com/free-vector/vector-illustration-cosmonaut_1441-11.jpg",
                            price:  120 ,
                            Location:"Nasa,USA",
                            inventory:5,
                            },
    
]